server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luna_db?serverTimezone=Asia/Seoul
    username: luna
    password: luna
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
cloud:
  aws:
    s3:
      bucket: boards11
    stack:
      auto: false
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      accessKey: AKIA5FTZFRIBVAM4QF7A
      secretKey: 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

  spring:
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

logging:
  level:
    com:
      laluna:
        laluna: debug